// <auto-generated />
using System;
using MVP.Date;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVP.Migrations
{
    [DbContext(typeof(AppDB))]
    [Migration("20230924001842_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MVP.Date.Models.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("category")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("countName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("factCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("factPayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("factPrice")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("planCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("planPayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("planPrice")
                        .HasColumnType("int");

                    b.Property<int>("projId")
                        .HasColumnType("int");

                    b.Property<string>("provider")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("taskId")
                        .HasColumnType("int");

                    b.Property<string>("taskName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("DBMaterial");
                });

            modelBuilder.Entity("MVP.Date.Models.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("adr")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("factFinishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("factMaterialPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("factStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("factWorkPrice")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("planFinishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("planMaterialPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("planStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("planWorkPrice")
                        .HasColumnType("int");

                    b.Property<string>("supervisor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("DBProject");
                });

            modelBuilder.Entity("MVP.Date.Models.Task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("factFinishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("factMaterialPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("factPayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("factPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("factStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("materials")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("necesseMaterials")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("parentTaskId")
                        .HasColumnType("int");

                    b.Property<string>("parentTaskName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("planFinishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("planPayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("planStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("planedMaterialPrice")
                        .HasColumnType("int");

                    b.Property<int>("planedPrice")
                        .HasColumnType("int");

                    b.Property<int>("prijId")
                        .HasColumnType("int");

                    b.Property<string>("supervisor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("DBTask");
                });

            modelBuilder.Entity("MVP.Date.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("mail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("passvord")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("post")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("seurname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("token")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("DBUser");
                });
#pragma warning restore 612, 618
        }
    }
}
